### ISSUE TITLE
[TASK]:  @cloudoperators/juno-ui-components Integrate TypeScript to UI Components 

### ISSUE THREAD

**Issue by andypf** [cloudoperators/juno#161]
**Task Description**
Migrate all components in the ui-components package from JavaScript to TypeScript to improve type safety and maintainability.

**Sub-tasks**

- [x] Integrate TSconfig
- [x] Fix tests and integrate Vitest
- [x] Makes Storybook works

**Related Issues**
- #160 
- #162

**Comment by barsukov** [comment]
I would change this task to Integration typescript but create a separate Epic for this one

**Comment by barsukov** [comment]
I would close this task cause the first integration of TS was done.
