### ISSUE TITLE
[TASK](infra): Add CodeQL code vulnerability check

### ISSUE THREAD

**Issue by edda** [cloudoperators/juno#172]
**Task Description**
Add a code vulnerability check to our PRs using [CodeQL](https://codeql.github.com/]. There's [prior art](https://github.com/cloudoperators/heureka/blob/main/.github/workflows/codeql.yaml) in the heureka repo.

**Sub-tasks**

- [ ] Add check that can be run locally
- [x] Add a workflow so the check runs automatically for every PR

**Comment by andypf** [comment]
In the GitHub repository under the security settings, there's an option to enable a built-in CodeQL check. We recently activated it, and it now runs code checks on every PR as expected.

However, we haven't yet found a way to run these checks locally.

**Comment by andypf** [comment]
I think this is sufficient for now. We can start by running the checks exclusively on GitHub, and if a local solution becomes necessary later, we can explore it then.
