### ISSUE TITLE
Discussion(Setup): Should we migrate UIs in Greenhouse to CloudOperators/Juno?

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#207]
### Issue: Repository Migration Strategy

We need to decide on the best approach for managing our Juno and Greenhouse projects. Here are two potential strategies:

#### **Strategy 1: Migrate Greenhouse Projects into a New Structure (Juno Style)**
We'll replicate the Juno setup (using Turborepo) within the Greenhouse repo. The Greenhouse app will be under `apps/greenhouse`, and extensions will go to `packages` like `packages/heureka`.

**Pros:**
- Consistent structure across projects.
- Modular organization (clear separation of core and extensions).
- Scalable with Turborepo’s monorepo setup.
- Flexibility to customize specifically for Greenhouse.

**Cons:**
- Duplicates setup effort, leading to inefficiencies.
- Higher maintenance overhead (keeping configurations in sync).
- Potential learning curve for developers switching between repos.
- Complicated dependency management.
- Monorepo with Backend code Go code

#### **Strategy 2: Migrate Everything Under the Juno Repo**
We consolidate Greenhouse projects and extensions into the existing Juno repo, creating a unified monorepo. App like `apps/greenhouse` and extensions like `packages/extensionOne`

**Pros:**
- Simplifies version control and CI/CD.
- Streamlines collaboration and reduces duplication of effort.
- Centralized dependency management.
- Easier code refactoring and sharing.
- Better DX.

**Cons:**
- Larger, more complex codebase to manage.
- CI/CD pipelines could become more complicated.
- Reduced modularity (projects become more coupled).
- More challenging access control.
- Higher potential for merge conflicts.
- Hard to keep track on less experience developers.

---

**Conclusion:**  
We need to weigh the benefits of consistency and modularity (Strategy 1) against the simplicity and efficiency of a unified repo (Strategy 2). Let's discuss which approach best suits our long-term goals.

**Comment by hgw77** [comment]
Note: as reminder, the reason why we do not want to put also `elektra2` (aka `aurora`) into the juno repo.

1. `aurora` will be a full stack app with frontend and backend part
2. we want to establish a community
3. we want to have a clear scope as openstack frontend
