### ISSUE TITLE
[TASK](ui): Migrate Badge(All dependable at once) to typescript

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#213]
### Task Description

We need to convert Badge and all related components from @cloudoperators/juno-ui-components to TypeScript

**List of potential dependencies**
Check what would be easy to migrate, this can be a problem
- Icon

**Sub-tasks**

- [x] change the name to .tsx of all related components
- [x] Change the stories to .tsx and all related componetns
- [x] fix all errors related to npm run typecheck
- [x] Transfer all related tests to vitests from jest
- [x] Check if npm run build is working and prove the working parts in storybook or example app
- [x] Check that npm run lint is working correctly and fix all tslint errors

**Related Issues**
- #168 

**Additional Context**
Please check this online codemode editor to change the PropTypes to a proper Ts interfaces

https://github.com/mskelton/ratchet
Online editor: https://ratchet.mskelton.dev/

We need to be pretty concious about migration to ts cause it could create a potential breaking changes. Also if there will be too much changes at once maybe consider to split up the task again. Also some dependencies could be hidden and only discovered while executing the migration, could also lead to potential reconsidering the order of task execution.

**Comment by guoda-puidokaite** [comment]
**Bug Found**

**Issue:** An icon isn't rendered for the Critical variant in Badge
**Description**: During the Typescript migration it was found that a 'critical' icon doesn't exist and that instead we default to `help` (see screenshot below). Thank You, @barsukov! 
<img width="717" alt="Screenshot 2024-10-14 at 16 45 39" src="https://github.com/user-attachments/assets/c02ecd2e-3dc3-472f-8395-39557d2c9500">

**Solution Questions:** 

- We've four icons for critical: `severityLow`, `severityMedium`, `severityHigh` and `severityCritical` (screenshot below). What's the intended behaviour for this variant type? Do we want to cover one general critical case or somehow cover four?
<img width="209" alt="Screenshot 2024-10-14 at 16 43 50" src="https://github.com/user-attachments/assets/c35311aa-64a1-4c1a-acc6-c1db6ed29727">

- If only one, what icon should be used for this variant? 


CC: @edda

**Comment by edda** [comment]
@guoda-puidokaite re: critical variant
This variant shouldn't exist. It's some accidental left-over that wasn't noticed before. Good job finding the bug and please just remove the `critical` variant

**Comment by guoda-puidokaite** [comment]
Nice! Super happy to hear that, as this variant was one of my UX concerns. Thanks for the quick reply. 🚀
