### ISSUE TITLE
[TASK](ui): Migrate Box component to TypeScript

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#214]
### Task Description

We need to convert Box and all related components from @cloudoperators/juno-ui-components to TypeScript

**List of potential dependencies**

- Nice candidate to migrate first, no deps for first glance but could be used inside other components.

**Sub-tasks**

- [x] change the name to .tsx of all related components
- [x] Change the stories to .tsx and all related componetns
- [x] fix all errors related to npm run typecheck
- [x] Transfer all related tests to vitests from jest
- [x] Check if npm run build is working and prove the working parts in storybook or example app
- [x] Check that npm run lint is working correctly and fix all tslint errors

**Related Issues**
- #168 

**Additional Context**
Please check this online codemode editor to change the PropTypes to a proper Ts interfaces

https://github.com/mskelton/ratchet
Online editor: https://ratchet.mskelton.dev/

We need to be pretty concious about migration to ts cause it could create a potential breaking changes. Also if there will be too much changes at once maybe consider to split up the task again. Also some dependencies could be hidden and only discovered while executing the migration, could also lead to potential reconsidering the order of task execution.

**Comment by guoda-puidokaite** [comment]
The naming of the `unpad` prop seems a little confusing and colloquial.
Something like `noPadding` = `true` might be more straightforward?

For example:
<img width="723" alt="Screenshot 2024-10-17 at 13 53 11" src="https://github.com/user-attachments/assets/1e14274c-05de-48b0-a981-acc28eed4f47">

However, this would of course be a breaking change and not within the scope of the ticket.
For now, I rephrased the docs to make things a little clearer.

<img width="1728" alt="Screenshot 2024-10-17 at 15 22 41" src="https://github.com/user-attachments/assets/b99972cd-aa43-498b-938e-2057c6d72d44">

FYI @edda
