### ISSUE TITLE
[TASK](ui): Migrate ContextMenu component to TypeScript

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#223]
### Task Description

We need to convert ContextMenu and all related components from @cloudoperators/juno-ui-components to TypeScript

**Note**: Component to be deprecated

**List of potential dependencies**

- Check files that used with ContextMenu.

**Sub-tasks**

- [x] change the name to .tsx of all related components
- [x] Change the stories to .tsx and all related componetns
- [x] fix all errors related to npm run typecheck
- [x] Transfer all related tests to vitests from jest
- [x] Check if npm run build is working and prove the working parts in storybook or example app
- [x] Check that npm run lint is working correctly and fix all tslint errors

**Related Issues**
- #168 

**Additional Context**
Please check this online codemode editor to change the PropTypes to a proper Ts interfaces

https://github.com/mskelton/ratchet
Online editor: https://ratchet.mskelton.dev/

We need to be pretty concious about migration to ts cause it could create a potential breaking changes. Also if there will be too much changes at once maybe consider to split up the task again. Also some dependencies could be hidden and only discovered while executing the migration, could also lead to potential reconsidering the order of task execution.

**Comment by guoda-puidokaite** [comment]
Migration has been started on branch `guoda-convert-contextmenu-to-ts`. However, `Menu` is used in the story, causing type issues. Waiting for an update on https://github.com/cloudoperators/juno/issues/237.
