### ISSUE TITLE
[TASK](ui): Migrate Form(All Related) component to TypeScript 

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#228]
### Task Description

We need to convert Form and all related components from @cloudoperators/juno-ui-components to TypeScript

**List of potential dependencies**

- Check files that used with Form, FormHint, FormRow, FormSection

**Sub-tasks**

- [x] change the name to .tsx of all related components
- [x] Change the stories to .tsx and all related componetns
- [x] fix all errors related to npm run typecheck
- [x] Transfer all related tests to vitests from jest
- [x] Check if npm run build is working and prove the working parts in storybook or example app
- [x] Check that npm run lint is working correctly and fix all tslint errors

**Related Issues**
- #168 

**Additional Context**
Please check this online codemode editor to change the PropTypes to a proper Ts interfaces

https://github.com/mskelton/ratchet
Online editor: https://ratchet.mskelton.dev/

We need to be pretty concious about migration to ts cause it could create a potential breaking changes. Also if there will be too much changes at once maybe consider to split up the task again. Also some dependencies could be hidden and only discovered while executing the migration, could also lead to potential reconsidering the order of task execution.

**Comment by gjaskiewicz** [comment]
Need to re-add radio group as it was temporaily removed when doing TS migration

        <RadioGroup name="color-radios" label="In case you are not sure, select your true favorite color:">
          <Radio key="r-1" id="color-red" label="Red" value="red" />
          <Radio key="r-2" id="color-blue" label="Blue" value="blue" />
          <Radio key="r-3" id="color-green" label="Green" value="green" />
          <Radio key="r-4" id="color-yellow" label="Yellow" value="yellow" />
        </RadioGroup>
        
![image](https://github.com/user-attachments/assets/52181df8-d733-429a-b54b-bd56ef3363cc)

**Comment by gjaskiewicz** [comment]
Also checkboxes:
        <CheckboxGroup name="all-about-red" label="What is your opinion towards the color Red?">
          <Checkbox key="c-1" id="overrated" label="Red is vastly overrated" value="overrated" />
          <Checkbox key="c-2" id="blackisred" label="Black is better" value="blackisbetter" />
        </CheckboxGroup>

**Comment by guoda-puidokaite** [comment]
**Future Improvements** 🚀

- **UX of "success" hints**: Do we need "success" hints? Or should errors just disappear when valid? If something isn't an error it's a valid input. <img width="739" alt="Screenshot 2024-11-12 at 13 44 42" src="https://github.com/user-attachments/assets/4e37427b-d71f-4628-950d-7c0d8016d4f2">
- **"Mandatory/Error/Success" icons should always be accompanied by an error message**: The "required" icon isn't self-explanatory.<img width="721" alt="Screenshot 2024-11-12 at 13 42 52" src="https://github.com/user-attachments/assets/7a0b8136-5284-47d9-ad29-9656bbd97449">
- **Input validation handled outside form?:** Does the user validate input outside these components and then use the states to display feedback? If so, that makes sense. 🙈

**Comment by guoda-puidokaite** [comment]
@gjaskiewicz You'd like to add back these tests? https://github.com/cloudoperators/juno/issues/228#issuecomment-2331243369 https://github.com/cloudoperators/juno/issues/228#issuecomment-2333491706

**Comment by guoda-puidokaite** [comment]
@gjaskiewicz I added back https://github.com/cloudoperators/juno/issues/228#issuecomment-2331243369 and https://github.com/cloudoperators/juno/issues/228#issuecomment-2333491706 as in PR https://github.com/cloudoperators/juno/pull/296/files#diff-74ba391d875641b60205df6ecdc535f7567ed3eb031ba6e02fc045f406cbe1e5
