### ISSUE TITLE
[TASK](ui): Migrate SearchInput component to TypeScript 

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#247]
### Task Description

We need to convert SearchInput and all related components from @cloudoperators/juno-ui-components to TypeScript

**List of potential dependencies**

- Check files that used with SearchInput

**Sub-tasks**

- [x] change the name to .tsx of all related components
- [x] Change the stories to .tsx and all related componetns
- [x] fix all errors related to npm run typecheck
- [x] Transfer all related tests to vitests from jest
- [x] Check if npm run build is working and prove the working parts in storybook or example app
- [x] Check that npm run lint is working correctly and fix all tslint errors

**Related Issues**
- #168 

**Additional Context**
Please check this online codemode editor to change the PropTypes to a proper Ts interfaces

https://github.com/mskelton/ratchet
Online editor: https://ratchet.mskelton.dev/

We need to be pretty concious about migration to ts cause it could create a potential breaking changes. Also if there will be too much changes at once maybe consider to split up the task again. Also some dependencies could be hidden and only discovered while executing the migration, could also lead to potential reconsidering the order of task execution.

**Comment by guoda-puidokaite** [comment]
**'onKeyPress' is deprecated 🔻**

<img width="730" alt="Screenshot 2024-10-17 at 09 12 44" src="https://github.com/user-attachments/assets/40bf51fd-a754-4fc3-bb00-a90414aea716">

CC: @edda

**Comment by edda** [comment]
> **'onKeyPress' is deprecated 🔻**
> 
> <img alt="Screenshot 2024-10-17 at 09 12 44" width="730" src="https://private-user-images.githubusercontent.com/121792659/377376845-40bf51fd-a754-4fc3-bb00-a90414aea716.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjgwNjUsIm5iZiI6MTcyOTE2Nzc2NSwicGF0aCI6Ii8xMjE3OTI2NTkvMzc3Mzc2ODQ1LTQwYmY1MWZkLWE3NTQtNGZjMy1iYjAwLWE5MDQxNGFlYTcxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxMjIyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjVmZDUzMWI1YjRjNTkzMzRlMTg3NmZmMDcwOTBiNDdmMjg2ZGJjMGY3MTgzNzRmYWVhMThiMTYyMzkxYTJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._3-L7YgyW819Uf1iyliJITQG_sVvvFy677SsBafb-54">
> Note: If we change it, would be really nice to rename the `SearchInput` prop to `onKeyDown` too
> 
> CC: @edda

Removing `onKeyPress` completely would be a breaking change. What I would do as a first step is add a `onKeyDown` handler (that does the same thing as the current `onKeyPress` handler and ensure the `onKeyPress` prop is marked as deprecated. Then when we release the next major version we can remove it together with the other deprecated components and options.

However, having said all that, there are other components that also have `onKeyPress` handlers (`Pagination` comes to mind, maybe others, too). They should all be changed at the same time. I'll add it to our ui-components umbrella epic.

**Comment by guoda-puidokaite** [comment]
Perfect, Thank You.
