### ISSUE TITLE
chore(url-state-provider): Roll out version 2

### ISSUE THREAD

**Issue by edda** [cloudoperators/juno#279]
Preparation:
- [ ] https://github.com/cloudoperators/juno/issues/191
- [ ] Announcement for QA und Prod
- [ ] Announce Docu of Changes / Tool in ReadMe

Tool: 
- [ ] https://expert-disco-g6nz18l.pages.github.io/

Todo:

- [ ] Please make a note to update the deeplinks used in alerts in sync with your deployment, e.g. Please update [helm](https://github.com/sapcc/helm-charts/blob/master/system/doop-central/alerts/infra-frontend/violation.alerts)

**Comment by TilmanHaupt** [comment]
Closed till routing and greenhouse is refactored.
