### ISSUE TITLE
[Bug](infra): fix release required checks for changeset

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#320]
**Description**
The problem that current changeset release PR crated from bot need required checks to be passed on main branch but it does not work this way cause it run checks not inside the PR and somewhere else.

**Steps to Reproduce**

1. PR from changeset bot

**Expected Behavior**
Probably the easiest solution after devbugging is to skip the checks for this particular PR but we do not know
**Screenshots**
<img width="981" alt="Bildschirmfoto 2024-09-09 um 14 23 42" src="https://github.com/user-attachments/assets/1d04bd0c-6289-4642-8b47-31b95f004248">

- OS: [e.g., Windows, macOS, Linux]
- Browser: [e.g., Chrome, Firefox, Safari]
- Version: [e.g., 22]

**Additional Context**

**Comment by edda** [comment]
Workaround:
* close PR
* reopen PR
* checks will run

Current theory:
* changeset bot doesn't have correct permissions
