### ISSUE TITLE
[Discuss](juno): Feedback on Migration to Monorepo with Changeset and Husky & co

### ISSUE THREAD

**Issue by TilmanHaupt** [cloudoperators/juno#333]
We are in the process of migrating to a monorepo structure with new tooling. To ensure a smooth transition, we are collecting feedback on potential improvements and any pain points which should be evaluated and maybe mitigated.

Please share: 
- Improvement Ideas: Suggestions for enhancing the migration process or tools.
- Pain Points: Any challenges or issues you've faced that we should address.

**Comment by TilmanHaupt** [comment]
Does the linter need to run on push, if he already ran for every commit?

**Comment by edda** [comment]
Pretter should not check `*.md` files. It's super annoying when you make a quick change to a readme online and then the prettier check fails.

**Comment by hodanoori** [comment]
After executing `npm run clean`, the turbo is also deleted. You should afterwards either execute `npm i ` or `npm install` to install turbo again. Is there any other workaround to install turbo only once?

**Comment by TilmanHaupt** [comment]
I often fail on get everything running. the docu with getting started and stuff like `npm run turbo build` dont work.

**Comment by ArtieReus** [comment]
We will create tasks for these topics and close this discussion:
- remove Format/Prettier checks for markdown files
- install turbo globally in the workspaces so it doesn't get remove with `npm run clean`. @andypf and @hgw77 will write documentation to it.
