### ISSUE TITLE
chore(setup): decide on folder structure and naming

### ISSUE THREAD

**Issue by edda** [cloudoperators/juno#39]
Decide on and implement the folder structure we want to use within the Juno repo for the projected contents, i.e. packages that can be libs, apps, or MFEs.

- belongs to #40 

- [x] Decide folder structure
- [x] Decide folder naming conventions
- [x] Create a markdown file

**Comment by andypf** [comment]
We can keep the directory structure flat and include the scope and type in the name of the asset:
Example: `elektra-mfe-compute` or `juno-lib-ui-components`. I really think we should rename juno-ui-components to ui-components. 

It remains to be decided whether we want to reflect the scope and type in package.json and also enter elektra-mfe-compute under name?

**Comment by andypf** [comment]
Naming decision: https://github.com/cloudoperators/juno/blob/main/docs/decision_naming_schema.md
