### ISSUE TITLE
[Task](ci): fix formatting for markdown files in PRs

### ISSUE THREAD

**Issue by ArtieReus** [cloudoperators/juno#453]
**Task Description**
When online editing a markdown file in Github there is often a problem that the format check fails which makes it necessary to check out the file locally to fix formatting. We should turn off md formatting in PRs.

**Sub-tasks**

- [ ] Review ci-test workflow

**Related Issues**
Link to related issues or tasks, if any.

**Additional Context**
Add any other context or information here.

**Comment by andypf** [comment]
Solution was provided by Taimoor:

- Override the Default HTML Formatter with Prettier in Workspace Settings JSON:
```
"[html]": { "editor.defaultFormatter": "esbenp.prettier-vscode"},
```

**Comment by andypf** [comment]
We resolve the issue of markdown files being excluded from CI checks by overriding the --check argument of the Prettier command in the workflow.
