### ISSUE TITLE
research(carrier-app): Scaffold the Carrier App

### ISSUE THREAD

**Issue by andypf** [cloudoperators/juno#51]
Set up the foundational framework for the Carrier App within the juno-core project. This involves establishing the core structure, essential dependencies, and initial functionalities to provide a robust starting point for ongoing development. The objective is to create a stable base that facilitates future feature enhancements and improvements.

- belongs to #43 

- [ ]	Create the basic structure
- [ ]	Develop a communication infrastructure to enable connections between MFEs and the host, as well as between multiple MFEs.
- [ ]	Integrate Navigation into the Carrier App to link the Menu with MFEs.
- [ ]	Implement intelligent URL-based state management.

**Comment by edda** [comment]
Closing. Will create new issues once architecture ADR completed
