### ISSUE TITLE
[Task](design): Release an initial version of our planned design guidelines document

### ISSUE THREAD

**Issue by edda** [cloudoperators/juno#592]
**Task Description**
Release an initial version of a design document that will serve as a reference guide for app developers using our design system. The design document will contain guidelines and UX patterns aimed at standardizing frontend app development.

**Sub-tasks**

- [ ] Make initial design document available to team

**Related Issues**
- #277
- #418

**Comment by martawright** [comment]
**Sharing Juno documetation**
Explore credentials and permission so that Anyone with SAP email address can view and comment on prototype file
