### ISSUE TITLE
[Task](documentation): document TypeScript Bootcamp Results  

### ISSUE THREAD

**Issue by ArtieReus** [cloudoperators/juno#597]
**Task Description**
Document the insights and recommendations from the TypeScript bootcamp, focusing on:
- **Development Setup**: Key points for setting up a TypeScript environment effectively.
- **Package Configuration**: Important considerations when configuring packages for TypeScript.
- **Migrating Files to TypeScript**: Best practices and tips for migrating files to TypeScript.
- **Anything else comes to your mind**: Any additional insights or helpful notes from the meeting.

**Sub-tasks**

- [ ] Add the documentation to the `ui-docs` repository. Consider creating a new section within `notes` for storing TypeScript-related documentation and any future related insights.

**Additional Context**
- **Meeting Minutes**: Reference the meeting minutes [here](https://minutes.tools.sap/#/events/CCD7kFXMe0nIaBvFqefB8) for additional context.

**Comment by TilmanHaupt** [comment]
raw material https://minutes.tools.sap/#/events/CCD7kFXMe0nIaBvFqefB8
