### ISSUE TITLE
[BUG](supernova): Non array values in FilterPills lead to failed render

### ISSUE THREAD

**Issue by TilmanHaupt** [cloudoperators/juno#609]

**Comment by guoda-puidokaite** [comment]
We've the same issue in `PredefinedFilters` component [here](https://github.com/cloudoperators/juno/blob/c9190d032ba59c70987bc1298d3838abd4c7a7aa/apps/supernova/src/components/filters/PredefinedFilters.jsx#L28).

**Comment by TilmanHaupt** [comment]
> We've the same issue in `PredefinedFilters` component [here](https://github.com/cloudoperators/juno/blob/c9190d032ba59c70987bc1298d3838abd4c7a7aa/apps/supernova/src/components/filters/PredefinedFilters.jsx#L28).

directly done
