### ISSUE TITLE
chore(storybook) default story book to the github pages

### ISSUE THREAD

**Issue by ArtieReus** [cloudoperators/juno#90]
- [x] Decide what else should be hosted in juno github pages
- [x] Remove old deployment
- [x] Fix link from side navigation Juno UI logo to github pages

**Comment by andypf** [comment]
To avoid outages, we should run a Cypress test against the Storybook to be deployed. The test itself can be very simple; it should just check if the homepage is accessible.

**Comment by edda** [comment]
For now instead of a cypress test we will use the new PR deployment feature
